version: '3.8'

services:
  image: mysql
  container_name: mysql_server
  environement:
    MYSQL_ROOT_PASSWORD: 123456
  ports:
    - 3306:3306
  volumes:
    - $$PWD/data:/var/lib/mysql
  restart: always

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports:
    - 8080:80
  links:
    - mysql_server:db
  restart: always
