version: '3.8'

services:
  mysql_server:
    image: mysql
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    networks:
      - bdd
    restart:
      always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_server
    ports:
      - 8080:80
    networks:
      - bdd
    depends_on:
      - mysql_server
    restart:
      always

networks:
  bdd: