version: "3.8"

services:
  db:
    image: mariadb:10.5
    container_name: db
    env_file:
      - .env
    networks:
      - bdd
    restart:
      always

  api:
    ## build: ./app
    build: ./app
    container_name: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bdd
    restart:
      always
networks:
  bdd:
