name: TP3_DOCKER_Louis
run-name: ${{ github.author }} TP3 Docker


# Créer une pipeline adaptée à ce projet Node.JS
# tests, docker image build, docker image push par exemple
# workdir: louis/TP_DOCKER_2/app

defaults:
  run:
    working-directory: louis/TP_DOCKER_2/app

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  docker-push:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tp3_docker:latest .
      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tp3_docker:latest
