name: TP3_DOCKER_Louis
run-name: ${{ github.author }} TP3 Docker


# Créer une pipeline adaptée à ce projet Node.JS
# tests, docker image build, docker image push par exemple
# workdir: louis/TP_DOCKER_2/app

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./louis/TP_DOCKER_2/app
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build
        run: npm run build --if-present
        working-directory: ${{env.working-directory}}
      - name: Test
        run: npm test
        working-directory: ${{env.working-directory}}
      - name: Docker build
        run: docker build -t louis/tp3_docker .
        working-directory: ${{env.working-directory}}
      - name: Docker push
        run: docker push louis/tp3_docker
        working-directory: ${{env.working-directory}}